spring:
  datasource:
    url: jdbc:h2:file:~/test_db
    driver-class-name: org.h2.Driver
    username: h2user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true